<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 10,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 11,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 12,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 13,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2019-11-02 07:38:20',
                'updated_at' => '2019-11-02 07:38:20',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2019-11-02 07:38:21',
                'updated_at' => '2019-11-02 07:38:21',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2019-11-02 07:38:21',
                'updated_at' => '2019-11-02 07:38:21',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2019-11-02 07:38:21',
                'updated_at' => '2019-11-02 07:38:21',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 13,
                'created_at' => '2019-11-02 07:38:22',
                'updated_at' => '2019-11-02 07:38:22',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Products',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2019-11-03 05:34:16',
                'updated_at' => '2019-11-03 05:34:16',
                'route' => 'voyager.products.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'P-Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2019-11-03 05:50:02',
                'updated_at' => '2019-11-16 12:12:02',
                'route' => 'voyager.category.index',
                'parameters' => 'null',
            ),
            16 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Category Products',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list-add',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2019-11-16 12:12:49',
                'updated_at' => '2019-11-16 12:12:49',
                'route' => 'voyager.category-product.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Coupons',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-basket',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2019-11-16 12:18:33',
                'updated_at' => '2019-11-16 12:18:33',
                'route' => 'voyager.coupons.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Orders',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-ticket',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2019-11-16 13:05:20',
                'updated_at' => '2019-11-16 13:05:20',
                'route' => 'voyager.orders.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Order Products',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dashboard',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 20,
                'created_at' => '2019-11-16 13:14:14',
                'updated_at' => '2019-11-16 13:14:14',
                'route' => 'voyager.order-product.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}